create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    nome text not null,
    idade integer not null check (idade >= 0),
    created_at timestamptz not null default now()
);
